sudo: required
services: 
  - docker

before_install:
  - docker build -t oscar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true oscar/react-test npm test

after_success:
  - docker build -t oscar/multi-client ./client
  - docker build -t oscar/multi-nginx ./nginx
  - docker build -t oscar/multi-server ./server
  - docker build -t oscar/multi-worker ./workerdocker login
  # Login in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push oscar/multi-client
  - docker push oscar/multi-nginx
  - docker push oscar/multi-server
  - docker push oscar/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'oscar-multi-docker'
  env: 'Oscarmultidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-906161076658'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


branches:
  only:
    - master


